export const SUBMIT_NEW_LIST = 'SUBMIT_NEW_LIST'
export const SUBMIT_LIST_FAILED = 'SUBMIT_LIST_FAILED'
export const SUBMIT_LIST_SUCCESS = 'SUBMIT_LIST_SUCCESS'

export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS' 
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED'
export const FETCHING_LISTS = 'GET_LISTS'

